### ISSUE TITLE
Attempt to call a nil value (global 'WebSocket')

### ISSUE THREAD

**Issue by vapidgod** [lampysprites/pribambase#11]
-Opened connection in Blender.
-Attempted to do File > Synx on Aseprite.

![hhhhhhhhhhhhhhhhhhhhhh](https://user-images.githubusercontent.com/74532509/140929957-6e0808d1-50b0-47b9-af32-47740ee83c28.PNG)

pribambase version 2.01 Blender 2.92 Aseprite 1.3-beta7

**Comment by lampysprites** [comment]
It says that the bit of functionality that the plugin uses is not available. Generally it's a sign that the script is running in an old version of aseprite, or in a build with websocket disabled. Could there be several versions installed?

Can you please run this piece of code ([script file](https://www.dropbox.com/s/1u46gfgifopqx3d/vercheck.lua?dl=1))
```lua
print(app.version)
print(app.apiVersion)
print(WebSocket == nil)
```
and confirm that it looks like this
![image](https://user-images.githubusercontent.com/49268426/140934922-9679ee35-09e9-456a-81c5-f577e09393e6.png)

If you're compiling aseprite yourself, try adding `-DENABLE_WEBSOCKET=ON` to cmake options

**Comment by lampysprites** [comment]
also metioned @ https://itch.io/t/1759969/aesprite-sync-issue 

The latest patch (0.3) has a version checking bit that displays a human-friendly messages. Leaving the issue open for now in case it's not sufficient
