### ISSUE TITLE
Blender 3.0

### ISSUE THREAD

**Issue by acqrn** [lampysprites/pribambase#17]
It seems this addon doesn't work on Blender 3.0, the latest version of blender.

**Comment by lampysprites** [comment]
It does.

I'd love to hear what you've been trying to do that doesn't work, and if
there's any messages in blender's console (window>toggle system console)

**Comment by acqrn** [comment]
Actually It seems that when I try to recreate the problem again, it seems to work.. That's odd but all that was done was restarting blender.
