### ISSUE TITLE
Error when starting sync string.unpack call

### ISSUE THREAD

**Issue by ghost** [lampysprites/pribambase#18]
After enabling sync in Aesprite 1.3, and syncing with my blend file in Blender 3.0, Aesprite throws an error in Sync.lua line 576

![image](https://user-images.githubusercontent.com/61211385/145685685-b22a4ee6-b7dd-43fb-ac87-677be27f6cfd.png)

**Version info**
3.0- for Blender
1.3 - for Aseprite
2.1 according to blender Addon - for Pribambase
Win10 x64 - OS

**Comment by lampysprites** [comment]
Heyo! I re-tried with same version of everything, and it doesn't seem to immediately fail. Means it needs specific conditions to happen, so can you please provide more info:

- does it happen immediately upon connection or with a sprite already added?
- a list of textures in your blender file if that's okay, only the names no images. Can get it quckly by typni `D.images.keys()` in blender's python console (opened same way as e.g. UV editor)
- what will aseprite show after replacing the offending block (lines 574-579) with following code:
```
        print("blend file " .. blendfile)
        print("message size " .. ml)
        while offset < ml do
            local len = string.unpack("<I4", msg, offset)
            print("offset " .. offset .. " len " .. len)
            local name, flags = string.unpack("<s4I2", msg, offset)
            print("name " .. name)
            syncList[name] = flags
            offset = offset + 6 + len -- 6 is string:packsize("<s4I2")
        end
```
- did you update the addon or is it freshly installed
Sorry about the hassle

**Comment by WiredDreamcaster** [comment]
I'm sorry I haven't gotten to this yet, I'll try to have an update next weekend

**Comment by lampysprites** [comment]
AFK
