### ISSUE TITLE
Automatic "Send UV" refresh when UV changes in Blender

### ISSUE THREAD

**Issue by recatek** [lampysprites/pribambase#19]
**What for**

After changing UVs in Blender, I need to manually re-send UVs back to Aseprite using the menu option. It would be nice if this was automated, or on a timer I could configure (similar to the auto-reimport addon). I frequently tweak UVs as I'm drawing and it would save some keystrokes/clicking each time.

**How**

Either by detecting changes in the UV map (if this is possible in the Blender UI), or by setting up a configurable timer so it can just be resent every couple of seconds.

**Relevance**
Please classify it by leaving, removing, or adding list items

- It affects everyone using the tool
- It's a very repetitive task

**Comment by lampysprites** [comment]
There's a perf issue on every step, but some clunky solution can be doable. I'll look into it

**Comment by lampysprites** [comment]
Sooo I looked and and remebered why it isn't a thing. We've got no reliable way to track which sprites are opened/closed in aseprite, so it's hard to automatically decide where to send them to. And lso, multiple objects can appear in several UV maps, and it's a major pain to track all those combinations to recreate the maps (which also change from selecting faces - sound like it'll end up rather confusing).

What can be done is an option to watch UVs in one specified UV editor area. FIrst activated manually like now, but without re-activating after the edits. Also I reckon that requires a feature that blocks autosave but don't quote me on that yet.

Think it'll be an improvement? And won't it be confusing for new users?

**Comment by recatek** [comment]
Is there a way to store the filename for the sprite you're syncing from Aseprite->Blender and only sending to Aseprite if that's the current app.activeSprite?

**Comment by lampysprites** [comment]
Blender side doesn't know about anything happening in ase, and I would love
to avoid communication that includes awaiting a response. All data is
"pushed" without any checks. Doing that to actively will jam the connection
in this case, as an uv map is sometimes a 2k+ texture (takes time to draw
too)

My confusion is for a different reason - there's no actual correspondence
between objects/uv editor state/images. The displayed uv keeps changing
when editing other objects in the scene, and that will replace the uv's
with something undesired.. I personally often edit with a checker texture
in the uv editor, not the image the material uses. So there probably had to
be some state that remembers what is sent to what? Dunno what to do with
several uv editors either.. Or how that should be stopped. Doesn't fit
between my ears all at once :/

**Comment by recatek** [comment]
> Blender side doesn't know about anything happening in ase, and I would love
to avoid communication that includes awaiting a response.

Could Aseprite send Blender an "OK"/"Not OK" signal to send UV updates that would suspend or resume the process depending on which sprite is active in Aseprite? As in, Aseprite knows which sprite it's syncing to Blender (I think?) and any time it detects a change in the app.activeSprite away from that syncing sprite, it tells Blender to hold off on the UV updates until further notice?

> The displayed uv keeps changing when editing other objects in the scene, and that will replace the uv's with something undesired

I think this would probably be acceptable/understandable if you could turn on or off auto-updates. I personally wouldn't expect to use it all the time, only when I'm in that very iterative mode of tweaking a UV, redrawing in Aseprite, tweaking the UV again, drawing again, back and forth, something I find myself doing a lot recently. If I get the same results that I would get if I just manually clicked the menu option to send UVs to Active Sprite, I think that would be okay for at least this particular use case.

**Comment by lampysprites** [comment]
Got a basic working version, in [watch-uv](https://github.com/lampysprites/pribambase/tree/watch-uv) branch. Runs once a second, and for some reason sometimes fails to send the update occasionally.

Can be installed by downloading the zip and copying files over the installed addon at e.g. `%APPDATA%/Blender Foundation/Blender/3.0/scripts/addons/pribambase`; or copying pribambase/thirdparty/ folder into the archive, then installing normally. In blender, it's accessed via the sprite menu next to the old button.

So far it keeps sending the uvs from the selected objects as long as it isn't disabled - and to me it still feels way too persistent. In addition, I can't figure how to keep track of which image is open in a particular uv editor... now I just slapped a warning.

I hope you can try to test it somewhat extensively; in particular whether it gets in the way when working with several objects and images.

**Comment by lampysprites** [comment]
thinkng about ux.  think then perhaps with a bunch of extra work there's a way drop all "destination" controls when sending the uv, and make a single switch of whether to display the uv map in ase per sprite just like the animation...

though, the disadvantage of that will be that the control over UV drawing will be hidden in the preferences - received a couple complaints about that even with the current approach

**Comment by recatek** [comment]
Hm, trying the branch version (need to update the client sprites in `%AppData%/Aseprite` as well) and the automatic UV syncing doesn't seem to work for me.

**Comment by lampysprites** [comment]
added in the recent update (2.2.0)
