### ISSUE TITLE
Something wrong with the sent UV map in Aseprite

### ISSUE THREAD

**Issue by photodiode** [lampysprites/pribambase#21]
**Reality**
Sending a UV map to Aseprite yields a mix of the UV map and some graphics card framebuffer garbage, sometimes only garbage.

**Expectation**
To get a transparent layer with only the UV map outlines.

**Logs**
Shows nothing after `Info: Aseprite connected`

**Version info**
- Blender 3.0.1
- Aseprite 1.3 Beta 10
- Pribambase 2.2.0
- OS: Linux 5.14.21 (KDE on AMD using X11)

**Additional context**
![Screenshot from Aseprite](https://i.imgur.com/9uYRLi2.png)

It did work in the first released version, if I recall correctly.
I guess it can just as well be Blender or some recent graphics driver bug.

**Comment by lampysprites** [comment]
Not quite sure where to start with this, uv drawing only uses line shader which is built into blender and does not have texture parameters. Just checked that drawing overwrites anything previously in the offscreen buffer, so not an initialization issue either.

Can you please try running this from text editor - it's drawing code that will create (presumably) an empty image and add it to the image editor, called "Offscreen.001", "Offscreen.002", etc, a new one each run.

Then, remove the #'s before #bgl and see if the results change.

```py
import bpy, gpu, bgl
import numpy as np
from gpu_extras.batch import batch_for_shader
from mathutils import Matrix

nbuf = np.zeros((256,256, 4), dtype=np.uint8)
offscreen = gpu.types.GPUOffScreen(256,256)
shader = gpu.shader.from_builtin('2D_UNIFORM_COLOR')
batch = batch_for_shader(shader, 'LINES', {"pos": []})

with offscreen.bind():
    with gpu.matrix.push_pop():
        projection_matrix = Matrix.Diagonal((2.0, -2.0, 1.0))
        projection_matrix = Matrix.Translation((-1.0 + 1.0 / 256, 1.0 + 1.0 / 256, 0.0)) @ projection_matrix.to_4x4()
        gpu.matrix.load_projection_matrix(projection_matrix)

        #bgl.glClearColor(0.0, 0.0, 0.0, 0.0)
        #bgl.glClear(bgl.GL_COLOR_BUFFER_BIT)
        bgl.glEnable(bgl.GL_BLEND)
        bgl.glBlendFunc(bgl.GL_SRC_ALPHA, bgl.GL_ONE_MINUS_SRC_ALPHA)
        bgl.glLineWidth(1)
        bgl.glEnable(bgl.GL_LINE_SMOOTH)
        bgl.glHint(bgl.GL_LINE_SMOOTH_HINT, bgl.GL_NICEST)

        shader.bind()
        shader.uniform_float("color", (0, 0, 0, 1))
        batch.draw(shader)

    buffer = bgl.Buffer(bgl.GL_BYTE, nbuf.shape, nbuf)
    bgl.glReadPixels(0, 0, 256,256, bgl.GL_RGBA, bgl.GL_UNSIGNED_BYTE, buffer)

img = bpy.data.images.new(name="Offscreen", width=256, height=256, alpha=True)
img.pixels = [c/255 for c in nbuf.flat]
```

**Comment by photodiode** [comment]
With the two `glClear` lines I get a transparent image, without them I get the usual mess (this time some parts of Blender's splash art)

**Comment by lampysprites** [comment]
I'll add a shim for time being, but not really convinced that it's how it supposed to work: gpu module should handle the clearing without needing opengl. Might be worth asking blender devtalk.

**Comment by photodiode** [comment]
Thank you very much for the quick response, and thank you for the amazing plugin!
