### ISSUE TITLE
[UI] "Send UV" option not showing up

### ISSUE THREAD

**Issue by RogelioVR** [lampysprites/pribambase#27]
**Reality**
On start in Blender, the option "Send UV" is not showing up.

**Expectation**
On start in Blender (new file), making a new UV, the "Send UV" option is showing up

**Logs**

```
Info: Packed to memory image ""
ERROR: Image "" not available. Keeping packed image
Info: Packed to memory image ""
ERROR: Image "" not available. Keeping packed image
Info: Packed to memory image ""
ERROR: Image "" not available. Keeping packed image
Info: Packed to memory image ""
ERROR: Image "" not available. Keeping packed image
Info: Packed to memory image ""
ERROR: Image "" not available. Keeping packed image
Info: Packed to memory image ""
ERROR: Image "" not available. Keeping packed image
Info: Packed to memory image ""
ERROR: Image "" not available. Keeping packed image
Info: Packed to memory image ""
ERROR: Image "" not available. Keeping packed image
Info: Packed to memory image ""
ERROR: Image "" not available. Keeping packed image

```

**Version info**
- for Blender 3.1.2
- for Aseprite 1.2.40
- for Pribambase 2.3.0
- OS Windows 10 PRO v21H2 19044.2130

Evidence

![image](https://user-images.githubusercontent.com/25854570/201345998-e872da75-3516-4cb7-933b-411126645aa5.png)
![image](https://user-images.githubusercontent.com/25854570/201346079-2b52ba09-3654-4b8e-842c-5503a0fb6e5b.png)
![image](https://user-images.githubusercontent.com/25854570/201346537-407173c1-efa8-490e-a4ff-13ad431e710c.png)

**Comment by lampysprites** [comment]
Hello!

Sending UV became automatic a few versions ago. It's enabled in the sync window in aseprite, searate for each image.

If you wish to use it only manually, it can be disabled that in the UV setion of addon panel. Send button is on the right side of the UV editor and not in the menu.
