### ISSUE TITLE
error when adding pribambase materials 

### ISSUE THREAD

**Issue by Smiley-ball** [lampysprites/pribambase#28]
**Reality**
I am unaware of how i caused this error. or how to fix it

**Expectation**
i expected everything to work normally when i tried to make a new pixel texture but i keep getting said error

**Logs**
ck.
```
  File "C:\Users\jacob\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\pribambase\object.py", line 157, in execute
    raise RuntimeError()
RuntimeError

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Users\jacob\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\pribambase\object.py", line 157, in execute
    raise RuntimeError()
RuntimeError

location: <unknown location>:-1
```

**Version info**
i have tried using the all recent blender versions and im being met with the same error

**Comment by lampysprites** [comment]
Likely, there's no images in that file, to be used in material. Please try creating or importing an image normally like you would in blender, or with plugin's workflow ([docs](https://github.com/lampysprites/pribambase/wiki/How-Do-I...#start-painting-textures-with-aseprite)).

Also thanks for the report, I'll add an error message later.
