### ISSUE TITLE
Weird duplication bug while selected mesh is in edit mode.

### ISSUE THREAD

**Issue by EustaceCervidae** [lampysprites/pribambase#30]
Ok so, i was working normally with the add-on and sudelny the file started to lag really bad, i went into the file to see if there was something wrong and noticed i had like 5k+ meshes in the file for some reason, all duplicates of the objects i had selected and was editing the texture in Asesprite (see image 1)
![image](https://user-images.githubusercontent.com/111919901/222874493-f2dadcf5-090c-4fbd-afab-12cfe045c015.png)

This really scared me so i reseted my computer and decided to try again and then i noticed this bug started happening after i synched and started working with Pribambase. If you guys know what to do i would love to hear a solution since this add-on is phenomenal and i really want to continue using it

**Comment by lampysprites** [comment]
Hello

In which version of blender did that happen?

And can you try disabling "Sync Automatically" in UV section in addon preferences, and see if that stops happening.

**Comment by EustaceCervidae** [comment]
Yeah, there's something weird happening with the Sync UV. Tried disabling like you said and it stoped replicating the selected object. Im using Blender 3.4.1

**Comment by lampysprites** [comment]
Could you try to enable sync back, and replace files in `%appdata%\Blender Foundation\Blender\3.4\scripts\addons\pribambase` with ones attached:

[pribambase_maybe_fix.zip](https://github.com/lampysprites/pribambase/files/10892211/pribambase_maybe_fix.zip)

**Comment by EustaceCervidae** [comment]
LETS FUCKING GOOOO, thanks Lamp it solved the problem. I'll keep my eyes open if anything weird happens again
