### ISSUE TITLE
Aseprite plugin not installing in Linux?

### ISSUE THREAD

**Issue by frozenMeatpopsicle** [lampysprites/pribambase#31]
Clicking "Setup for Aseprite" opens up a blank Aseprite window with no prompts or notifications. This locks Blender. Closing Aseprite then frees Blender and comes up with the following error in Blender.

```
Aseprite extension setup failed. Make sure scripting is enabled in your version of Aseprite.
```
Not sure if there's something I'm supposed to be doing in Aseprite, or what "make sure scripting is enabled" means. Tutorial video doesn't show anything regarding this.

**Version info**
- Blender 3.4.0
- Aseprite 1.3 rc
- Pribambase. 2.4.2
- Linux Mint 21

**Comment by lampysprites** [comment]
that part was supposed to run a CLI script without opening the window.
maybe it'll help to change `setup.py` a bit
```patch
-- _, lines = getstatusoutput([aseprite_exe, "--batch", "--script", info_lua])
++ _, lines = getstatusoutput(f'"{aseprite_exe}" --batch --script "{info_lua}"'])
```

**Comment by frozenMeatpopsicle** [comment]
Yea, that does the trick. Thanks!

**Comment by lampysprites** [comment]
Had to change that part a bit after this fix, feel free to reopen if it regressed.
