### ISSUE TITLE
What is the proper way to save textures and spritesheets?

### ISSUE THREAD

**Issue by gulagkulak** [lampysprites/pribambase#37]
I created this animated computer using Blender, pribambase, and aseprite:
![animated_computer](https://github.com/lampysprites/pribambase/assets/144597589/2cff1d24-9bd8-432c-b9d5-2c089def6d3d)

When I saved the .blend file it saved a bunch of empty textures into a separate "textures" folder. **I'm trying to figure out the proper way of saving textures from Blender/aseprite into the "textures" folder.** Should I hit "save" in aseprite and overwrite the empty textures? Do I save the textures from inside Blender somehow?

I ended up saving the textures from inside aseprite and overwriting the empty png files inside the "textures" folder, so I could import the model into godot. That worked, but it doesn't seem like the intended way of doing it.

Also, the animation didn't show up in godot. I guess that's a godot issue, but do you have any idea how to get animated textures working inside godot?

**Comment by lampysprites** [comment]
From that description, not quite sure what you did there exactly.

Anyway, here's how it works. The addon creates all textures as [packed images](https://artisticrender.com/blender-pack-external-files-how-why-when/). They are considered a "previews" of original .ase file. Usually those textures get exported along with fbx/obj/etc, but you can also export them from aseprite directly, unpack, or whatever else. 

Also the addon syncs any image supported by blender normally, not just ones set up with it, so you could just load a .png as you'd normally do in blender, and then open it in connected aseprite, and paint.

There isn't really any restrictions imposed by using the addon, nor a preferred way to do things.

----

Regarding godot, you could export spritesheet (addon's/from aseprite), and then set up uv scaling and [movement](https://ask.godotengine.org/892/are-animated-uvs-currently-possible).

----

I also appreciate if you used itchio board for anything that is not a bug/suggestion.
